clusterName: turingpi
talosVersion: v1.10.6
endpoint: https://192.168.1.224:6443
allowSchedulingOnControlPlanes: true

controlPlane:
  patches:
    - &baselonghorn |-
      machine:
        kubelet:
          extraMounts:
            - destination: /var/lib/longhorn
              type: bind
              source: /var/lib/longhorn
              options:
                - bind
                - rshared
                - rw

worker:
  patches:
    - *baselonghorn

nodes:
  - hostname: "n1"
    ipAddress: 192.168.1.224
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        routes: &routes
          - network: 0.0.0.0/0
            gateway: 192.168.1.1
    schematic:
      customization: &customization
        systemExtensions:
          officialExtensions:
            - siderolabs/i915
            - siderolabs/iscsi-tools
            - siderolabs/util-linux-tools
  - hostname: "n2"
    ipAddress: 192.168.1.226
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        routes: *routes
    schematic:
      customization: *customization
  - hostname: "n3"
    ipAddress: 192.168.1.223
    installDisk: /dev/nvme0n1
    controlPlane: true
    networkInterfaces:
      - interface: eth0
        dhcp: true
        routes: *routes
    schematic:
      customization: *customization
  - hostname: "n4"
    ipAddress: 192.168.1.225
    installDisk: /dev/nvme0n1
    networkInterfaces:
      - interface: eth0
        dhcp: true
        routes: *routes
    schematic:
      customization: *customization