apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: manyfold
  namespace: default
spec:
  ingressClassName: tailscale
  defaultBackend:
    service:
      name: manyfold
      port:
        number: 3214
  tls:
    - hosts:
        - manyfold
