apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 5m
  chart:
    spec:
      chart: longhorn
      version: "1.8.1"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  values:
    defaultSettings:
      defaultReplicaCount: 2
      backupstorePollInterval: 300
      createDefaultDiskLabeledNodes: true
      guaranteedInstanceManagerCPU: 12
      guaranteedEngineManagerCPU: 12
      logLevel: info
      # Performance optimizations for SSDs
      concurrentReplicaRebuildPerNodeLimit: 5
      concurrentBackupRestorePerNodeLimit: 5
      # Storage settings
      storageNetwork: ""
      v2DataEngine: true
      # Monitoring
      defaultDataPath: /var/lib/longhorn
    persistence:
      defaultClassReplicaCount: 2
      defaultClass: true
    csi:
      attacherReplicaCount: 2
      provisionerReplicaCount: 2
      resizerReplicaCount: 2
      snapshotterReplicaCount: 2
      kubeletRootDir: /var/lib/kubelet
    # Node selector for worker nodes only
    nodeSelector:
      node-role.kubernetes.io/worker: ""
    # Priority class for critical components
    priorityClass:
      create: true
      value: 1000000 