apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: metrics-server
  namespace: metrics-server
spec:
  interval: 5m
  chart:
    spec:
      chart: metrics-server
      version: "3.12.*"
      sourceRef:
        kind: HelmRepository
        name: metrics-server
        namespace: flux-system
      interval: 1m
  install:
    createNamespace: true
  values:
    args:
      - --kubelet-preferred-address-types=InternalIP
    tls:
      type: cert-manager
      certManager:
        addInjectorAnnotations: true
        existingIssuer:
          enabled: true
          name: selfsigned-cluster-issuer
          kind: ClusterIssuer
