apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: loki
  namespace: lgtm
spec:
  interval: 5m
  chart:
    spec:
      chart: loki
      version: "5.41.4"
      sourceRef:
        kind: HelmRepository
        name: grafana
        namespace: lgtm
  values:
    loki:
      auth_enabled: false
      singleBinary:
        replicas: 2
        resources:
          limits:
            cpu: 1000m
            memory: 2Gi
          requests:
            cpu: 500m
            memory: 1Gi
        persistence:
          enabled: true
          size: 10Gi
          storageClass: longhorn
          accessMode: ReadWriteOnce
        retention_deletes_enabled: true
        retention_period: 168h  # 7 days
        chunk_store_config:
          max_look_back_period: 168h
        table_manager:
          retention_deletes_enabled: true
          retention_period: 168h
        limits_config:
          enforce_metric_name: false
          reject_old_samples: true
          reject_old_samples_max_age: 168h
          max_cache_fresh_items_per_query: 1000
          max_entries_limit_per_query: 5000
          max_query_length: 721h
          max_query_parallelism: 32
          cardinality_limit: 100000
          max_streams_per_user: 0
          max_global_streams_per_user: 0
          ingestion_rate_mb: 4
          ingestion_burst_size_mb: 6
          max_query_series: 500
          max_streams_matchers_per_query: 1000
          max_concurrent_tail_requests: 100
          max_cache_fresh_items_per_query: 1000
          max_entries_limit_per_query: 5000
          max_query_length: 721h
          max_query_parallelism: 32
          cardinality_limit: 100000
          max_streams_per_user: 0
          max_global_streams_per_user: 0
          ingestion_rate_mb: 4
          ingestion_burst_size_mb: 6
          max_query_series: 500
          max_streams_matchers_per_query: 1000
          max_concurrent_tail_requests: 100
        storage_config:
          filesystem:
            chunks_directory: /var/loki/chunks
            rules_directory: /var/loki/rules
          boltdb_shipper:
            active_index_directory: /var/loki/boltdb-shipper-active
            cache_location: /var/loki/boltdb-shipper-cache
            cache_ttl: 24h
            shared_store: filesystem
            index_gateway_client:
              server_address: loki-index-gateway:9095
        compactor:
          working_directory: /var/loki/compactor
          shared_store: filesystem
          compaction_interval: 10m
          retention_enabled: true
          retention_delete_delay: 2h
          retention_delete_worker_count: 150
          delete_request_cancel_period: 24h
          max_compaction_parallelism: 1
          compaction_timeout: 10m
          retention_delete_timeout: 5m
          max_compaction_parallelism: 1
          compaction_timeout: 10m
          retention_delete_timeout: 5m
        ruler:
          alertmanager_url: http://alertmanager:9093
          ring:
            kvstore:
              store: memberlist
          rule_path: /var/loki/rules
          storage:
            type: local
            local:
              directory: /var/loki/rules
          wal:
            dir: /var/loki/wal
        query_range:
          cache_results: true
          results_cache:
            cache:
              embedded_cache:
                enabled: true
                max_size_mb: 100
                validity: 24h
        frontend:
          compress_responses: true
          log_queries_longer_than: 5s
          downstream_url: http://loki:3100/loki/api/v1/query_range
          parallelise_shardable_queries: true
        index_gateway:
          ring:
            kvstore:
              store: memberlist
          storage:
            type: local
            local:
              directory: /var/loki/index
        memberlist:
          join_members:
            - loki-memberlist:7946
        server:
          http_listen_port: 3100
          grpc_listen_port: 9096
        common:
          path_prefix: /var/loki
          storage:
            filesystem:
              chunks_directory: /var/loki/chunks
              rules_directory: /var/loki/rules
          replication_factor: 2
          ring:
            kvstore:
              store: memberlist
            heartbeat_timeout: 1m
            heartbeat_interval: 10s
        monitoring:
          self_monitoring:
            enabled: false
        serviceMonitor:
          enabled: false
        service:
          type: ClusterIP
          port: 3100
        ingress:
          enabled: false
        podAnnotations:
          prometheus.io/scrape: "true"
          prometheus.io/port: "3100"
        podSecurityContext:
          fsGroup: 10001
          runAsNonRoot: true
          runAsUser: 10001
        containerSecurityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          readOnlyRootFilesystem: true
        nodeSelector:
          node-role.kubernetes.io/worker: ""
        tolerations:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
            effect: NoSchedule
        affinity:
          podAntiAffinity:
            preferredDuringSchedulingIgnoredDuringExecution:
              - weight: 100
                podAffinityTerm:
                  labelSelector:
                    matchExpressions:
                      - key: app.kubernetes.io/name
                        operator: In
                        values:
                          - loki
                  topologyKey: kubernetes.io/hostname