apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: tailscale-operator
  namespace: tailscale
spec:
  interval: 5m
  chart:
    spec:
      chart: tailscale-operator
      version: "0.1.0"
      sourceRef:
        kind: HelmRepository
        name: tailscale
        namespace: tailscale
  values:
    # Enable the operator to manage Tailscale nodes
    operator:
      enabled: true
    # Configure the operator to use your Tailscale auth key
    # You'll need to create this in your Tailscale admin console
    # and store it as a Kubernetes secret
    authKey:
      secretName: tailscale-auth-key
      secretKey: auth-key
