apiVersion: ENC[AES256_GCM,data:sx0=,iv:GSixz/DNZc3bQ9e03XPCqvCBO06C67Ly57sVzfFsyfY=,tag:khrQpIPxrIKA/dSSzSs17g==,type:str]
kind: ENC[AES256_GCM,data:FPSe+74R,iv:JNH2l1tNUSpV69RsXJUyfdlJx8ghcSR8dPEbjorXVUo=,tag:7tMAE7IAxGd8ISBIFwBTdQ==,type:str]
metadata:
    name: ENC[AES256_GCM,data:1rWSbJJKQf6I+7qVX0s=,iv:8h2xYPJDtBCJzWCfiCtmMcg5l5iOwub2YfDeZTRNILQ=,tag:ZcjZTnjfXBKY08BE0nD+Gg==,type:str]
    namespace: ENC[AES256_GCM,data:IojvC/B17boV,iv:AsaSneqt6bYJ2WAFBfRCLeOIIItBuMI6jJDeB1HT7/k=,tag:djTQocuwiuyCqFFyIciUNw==,type:str]
type: ENC[AES256_GCM,data:llBTEvO3,iv:762rOV/aD/Hjgi7d/SBAG+UXw5G/LxHtI1AD2+Ealik=,tag:EJoGOQ3kIpBwLyM7lN8prQ==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:VWtfwu1sUfQr19Fcn7epw9U=,iv:Xl2s7+VQJb4ClGT41aWmNbFNepWhNC8M7e9DZPET4Ug=,tag:2vkUSuTqQE0tkyPRo8Ig8w==,type:str]
    client_secret: ENC[AES256_GCM,data:XU+KaxMGqR8tyZ3Yq7QCg9CMINg3lTyerYSVErZE4ojTtiJfGsJEiqR7O0TXu7SCYuQQ9x+n1BG76X93w7DELQ==,iv:qDOwMp5zbL1cQGUzWaUBoXAxmTwHFbhfU2MztwdH274=,tag:p/F7XsEnIfYGqHkMz0KCZA==,type:str]
sops:
    age:
        - recipient: age1derzdv0akpyremxj0v5cvacng7sephxpcvpkmetqx8qjjpc4f4fqcxh5y5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBlQnM0cllxa3FHYUh0OTRk
            b05sblQ0Qm9pa0EzQkRXQ2o5T090THkxVmhjCnRWODVmUmFHZWkzNy9WWEFKMXJ6
            MlJKOUdnZzhuMzF1R2ZTYmZUMlR2ZEUKLS0tIFd4RkJMMkpHNTdKc000RWRRN0xP
            QlZoK212UlFGQ01yd2I0UnhqWEg4QUUKoornOIb/HKlXXEKCcjFpTjlX81OhFcwE
            T/9RWei/Z76ElwrOEXsax5s9XG6J3GWynSh6DJ57InQtR9BjP1YdRw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T04:42:25Z"
    mac: ENC[AES256_GCM,data:WMW9ib/+uLw2sIMIvG/cIqeDFzWrtwVl/g1qVb4b5X67izEOCT4g1NGg6l3MrOJIkT6nnU5UaiqnGfOvTzWocD89LvJ6APK63Lq2AYYzMeWOteShxpYAEEke0GAPdtDUV+ANkRkBcugzWtz5w04LxF4nwCCnwfu7PfebuofLaIg=,iv:GAEEweMP4fIQj+F5h4rrlQitZM9rClOwqPvBLaLHOXA=,tag:mP3Wjr7uT+ifS5Ny3f28mg==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
