apiVersion: ENC[AES256_GCM,data:QLo=,iv:NP5AkAInvQzlnzqUBMRi+xfvCxngDmDiGjXVMc90yCQ=,tag:FgVZhpoA9tFWBlCppNDeOA==,type:str]
kind: ENC[AES256_GCM,data:fskhV9J2,iv:IjxUFJZl26gMKXWeqXEk75CULWujTQy1kG+2CxEqAHA=,tag:OMw4RVOb7JymBnC4mIYtaA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:v+dHcwuPQmBizqNCgdM=,iv:lTYtsfZkg53j4aUgsU46ruTbIc1iOvZb1MfsZ9QSECY=,tag:oAHsSvPz+lKfzbtrERSXWA==,type:str]
    namespace: ENC[AES256_GCM,data:btgP2YfEORow,iv:p2yWXIGM8oFTiKU2rKwURFy5VzL++abHVqyE4KcaDuM=,tag:n3DI0M6yT6gfZnpJdzxlgg==,type:str]
type: ENC[AES256_GCM,data:+MgjtfrE,iv:8wl+Env+hos69NHo5PIoYY7w+7YIzkZpBAZG4CS/YTk=,tag:mInTo67NLagF1PcaJ9wCTg==,type:str]
stringData:
    client_id: ENC[AES256_GCM,data:Kq35tpke4WtL+cvSJQs1nVE=,iv:pfim3J09DcZdYkJ2X4LmlQtg5pSHaTs89E23Zt53o+Y=,tag:RHwahQx2ghhEFInHcNaEIQ==,type:str]
    client_secret: ENC[AES256_GCM,data:m32OUVI1vImKYmjyWpgOaeuBka+TRnNVs+tXhM+vQCO/L//uDWrSQOEZ1MuvbKnd++8iUuCf1odh+mkImTU3dA==,iv:AU4KjhvuvP3nCymEhAJlSdpPlvYfZ7tEaqUMfcqkcoE=,tag:Uv3TqBhOJNESslK3gMsIWA==,type:str]
sops:
    age:
        - recipient: age1derzdv0akpyremxj0v5cvacng7sephxpcvpkmetqx8qjjpc4f4fqcxh5y5
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAwTUZLZHlVY2hLS0VsN1dN
            N0x2TnBqc0NUTE1pOUsweGtyVzdTNUVJMndZClpoZ1VVclhMbndudVBmTmNZeEUw
            NTQyT1hZVmMyZlFCTGxPZVBjNEhhOWsKLS0tIEtMVVFEWEpTVVlQT1ZpOXV3dDRY
            Z1gxQVBSdkQ3YmtIVU1TdkwvUCtnNXMK3+646yAnybhBE89cMGclXAjqbVpHyZM8
            dpLxfIVMmIxNG8eQn0dVV0MjusYGNyH+OIksnE7A4jhgJM0neKiwMg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-03-02T04:34:33Z"
    mac: ENC[AES256_GCM,data:FkACBLnT5kC8HD/vE2ABjyp5QyY2hsWnRzB+6g3WHleFjVYkCuJzXoXpaTZXYuRDhPEGYulRq0a6IwmCrfzqmaf4VRKj8ezZD9Qswk80lMSyUSRYAWzoMO8Mo8izLwuvNV+0m/MTRAonegKVNImHaEzwxm+9/nKpY7++9cTnmck=,iv:2l3nexQ+ZFhGX9d/6nKcGWPHZuXAQKY+JzTksfnK2Ik=,tag:V3wzQtrSC6r1AxBdnh4HYA==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.11.0
